#!/bin/bash
# setup-usb-controllers.sh - Configure stable USB gamepad mapping by physical port
# Run this to identify USB ports and set up persistent controller ordering

LOG="/home/pi/arcade.log"
UDEV_DIR="/etc/udev/rules.d"
RULE_FILE="$UDEV_DIR/99-arcade-controllers.rules"

log() { echo "[$(date +'%Y-%m-%d %H:%M:%S')] USB-SETUP: $*" | tee -a "$LOG"; }

echo "=== USB Arcade Controller Setup ==="
echo ""
echo "This will create stable controller assignments based on USB physical port."
echo "Each USB port will always be the same player number."
echo ""

# Check if running as root for udev
if [ "$EUID" -ne 0 ]; then 
    echo "Note: Run with sudo if you want to install udev rules automatically"
    echo "      Without sudo, this will just show you the current mapping."
    echo ""
fi

# Show current joystick devices
echo "Current joystick devices:"
echo "---"
for js in /dev/input/js*; do
    if [ -e "$js" ]; then
        # Get the path symlink
        path_link=$(ls -la /dev/input/by-path/ 2>/dev/null | grep "$(basename $js)$" | awk '{print $9}')
        id_link=$(ls -la /dev/input/by-id/ 2>/dev/null | grep "$(basename $js)$" | awk '{print $9}')
        
        echo "  $js"
        [ -n "$path_link" ] && echo "    -> by-path: $path_link"
        [ -n "$id_link" ] && echo "    -> by-id:   $id_link"
    fi
done
echo ""

# Show udev info for each joystick
echo "USB port details (run 'udevadm info -a /dev/input/jsN' for more):"
echo "---"
for js in /dev/input/js*; do
    if [ -e "$js" ]; then
        devpath=$(udevadm info -q path "$js" 2>/dev/null)
        if [ -n "$devpath" ]; then
            echo "  $js: $devpath"
        fi
    fi
done
echo ""

# Interactive setup
if [ "$EUID" -eq 0 ]; then
    echo "Install udev rules for stable controller mapping?"
    read -p "(y/n): " confirm
    
    if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
        log "Installing udev rules for USB controllers..."
        
        # Create rules file based on current detected devices
        cat > "$RULE_FILE" <<'EOF'
# USB Arcade Controller Persistent Naming
# Auto-generated by setup-usb-controllers.sh
# Maps USB physical ports to stable player numbers

EOF
        
        # For each joystick, create a rule based on USB port location
        player=1
        for js in /dev/input/js*; do
            if [ -e "$js" ]; then
                # Get the path symlink to identify USB port
                path_target=$(readlink -f "/dev/input/by-path/$(ls -la /dev/input/by-path/ 2>/dev/null | grep "$(basename $js)$" | awk '{print $9}')" 2>/dev/null)
                
                if [ -n "$path_target" ]; then
                    # Extract USB port from path (e.g., usb-0:2 from xhci-hcd.1-usb-0:2)
                    usb_port=$(ls -la /dev/input/by-path/ 2>/dev/null | grep "$(basename $js)$" | grep -oE 'usb-[0-9]+:[0-9]+' | head -1)
                    
                    if [ -n "$usb_port" ]; then
                        # Convert usb-0:2 format to DEVPATH pattern
                        bus=$(echo "$usb_port" | cut -d: -f1 | sed 's/usb-//')
                        port=$(echo "$usb_port" | cut -d: -f2)
                        
                        cat >> "$RULE_FILE" <<EOF
# Player $player - USB bus $bus, port $port
SUBSYSTEM=="input", KERNEL=="js[0-9]*", ENV{DEVPATH}=="*usb$bus/$port*", SYMLINK+="input/arcade-p$player"

EOF
                        log "Player $player mapped to USB bus $bus, port $port"
                        player=$((player + 1))
                    fi
                fi
            fi
        done
        
        # Reload udev rules
        udevadm control --reload-rules
        udevadm trigger --subsystem-match=input
        
        log "Udev rules installed to $RULE_FILE"
        log "Created stable device names: /dev/input/arcade-p1, arcade-p2, etc."
        echo ""
        echo "=== Setup Complete ==="
        echo ""
        echo "Stable controller devices created:"
        ls -la /dev/input/arcade-p* 2>/dev/null || echo "  (Run 'udevadm trigger' if devices don't appear yet)"
        echo ""
        echo "Your controllers will now ALWAYS be:"
        cat "$RULE_FILE" | grep "^# Player" || true
        echo ""
        echo "To verify after reboot: ls -la /dev/input/arcade-p*"
    else
        echo "Skipping udev rule installation."
        echo ""
        echo "To manually create rules, edit: $RULE_FILE"
        echo "Use patterns like:"
        echo '  SUBSYSTEM=="input", KERNEL=="js[0-9]*", ENV{DEVPATH}=="*usb0/2*", SYMLINK+="input/arcade-p1"'
    fi
else
    echo "Run with 'sudo' to automatically install udev rules."
    echo ""
    echo "Or manually create: $RULE_FILE"
    echo "With content like:"
    echo 'SUBSYSTEM=="input", KERNEL=="js[0-9]*", ENV{DEVPATH}=="*usb0/2*", SYMLINK+="input/arcade-p1"'
fi

echo ""
echo "Note: Plug each controller into its intended USB port before running this script."
echo "      The physical USB port determines the player number, not the controller itself."
